# Task 1:
Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”
3
45 
 83
 21
Have a go at ‘w’ ‘r’  ‘a’


In [ ]:
my_file = open("Numbers", "w")



In [ ]:
my_file.write("3 \n45 \n83 \n21") #why can't I use with input function?
my_file.close()

In [ ]:
my_file = open("Numbers", "a")
my_file.write("3 \n45 \n83 \n21")
my_file.close()

In [ ]:
my_file = open("Numbers", "r")
# Can't write or append on "read" mode

# Task 2
Write a program to ask a student for their percentage mark and convert this to a grade

The conversion will be done in a function called mark_grade 


In [18]:
def mark_grade(inp_percen_mark):
    global grade
    if float(inp_percen_mark) > 0 and float(inp_percen_mark) <= 40:
        grade = "F"
        print("Your",inp_percen_mark,"percentage mark is", grade)
    elif float(inp_percen_mark) > 40 and float(inp_percen_mark) <= 50:
        grade = "D"
        print("Your",inp_percen_mark, "percentage mark is", grade)
    elif float(inp_percen_mark) > 50 and float(inp_percen_mark) <= 60:
        grade = "C"
        print("Your",inp_percen_mark, "percentage mark is", grade)
    elif float(inp_percen_mark) > 60 and float(inp_percen_mark) <= 70:
        grade = "B"
        print("Your",inp_percen_mark, "percentage mark is", grade)
    elif float(inp_percen_mark) > 70 and float(inp_percen_mark) <= 100:
        grade = "A"
        print("Your",inp_percen_mark, "percentage mark is", grade)
    else: print("wrong input")
    return

    ## I have to use: "global grade"
    ## otherwise I can't print out "grade" even I created it inside the function above?
    ## print(grade): there'd error for name error 

In [ ]:
mark_grade(15)

# Extension to Task 2:

Ask the user for their target grade and print this with their mark 
<br>
If their target grade > exam grade display a suitable message
<br>
If their target grade = exam grade display a suitable message
<br>
If their target grade < exam grade display a suitable message



In [21]:
def grade_noti():
    inp_grade = input("What is your mark (in percentage)?")
    exp_grade = input("what is your target grade")
    if float(inp_grade) < 0 or float(inp_grade) > 100:
        print("wrong value")
        quit()
    else: mark_grade(inp_grade) #run the function above to transform grade
    inp_grade = grade           #assign the result tranformed
    if float(exp_grade) < 0 or float(exp_grade) > 100:
        print("wrong value")
        quit()
    else: mark_grade(exp_grade) #run the function above to transform grade
    exp_grade = grade           #assign the result tranformed
    if inp_grade == exp_grade: # I consider condition of similar grade first, then exam grade is higher than target, and "else" for the exam grade is lower than target one
        print("Your exam grade is the same as your target grade")
    elif inp_grade != exp_grade:
        if inp_grade == "A":
             print("Your exam grade is higher than your target grade")
        elif inp_grade == "B" and exp_grade != "A":
            print("Your exam grade is higher than your target grade")
        elif inp_grade == "C" and (exp_grade != "A" and exp_grade != "B"):
            print("Your exam grade is higher than your target grade")
        elif inp_grade == "D" and (exp_grade == "E" or exp_grade == "F"):
            print("Your exam grade is higher than your target grade")
        elif inp_grade == "E" and exp_grade == "F":
            print("Your exam grade is higher than your target grade")
        else:
            print("Your exam grade is lower than target grade")
    return


In [24]:
grade_noti()

Your 40 percentage mark is F
Your 12 percentage mark is F
Your exam grade is the same as your target grade


# Numpy HTL:

Create a 1D array of numbers from 0 to 9 <br>
Create a 3×3 NumPy array of all Boolean value Trues <Br>
Extract all odd numbers from array of 1-10 <br>
Replace all odd numbers in an array of 1-10 with the value -1 <br>
Convert a 1D array to a 2D array with 2 rows <br>
Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals 


In [30]:
pip install numpy

You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [96]:
import numpy as np

In [126]:
array = np.arange(10) # Create a 1D array of numbers from 0 to 9
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [67]:
np.full([3,3], True) #Create a 3×3 NumPy array of all Boolean value Trues

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [133]:
array_3 = np.arange(1, 11) #create array from 1 to 10
print(array_3)
array_odd = np.delete(array_3, np.where(array_3 % 2 != 0)) # remove all odd numbers and assigned new array into new array named array_odd


[ 1  2  3  4  5  6  7  8  9 10]


In [143]:
# replace all odd numbers with -1
array_odd_1 = np.where(array_3 % 2 != 0, #condition elements are odd number
                                     -1, #then replaced with -1
                                      array_3) #otherwise remains
                                      
print(array_odd_1)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [153]:
#Convert a 1D array to a 2D array with 2 rows
array_2D = array.reshape(5, 2)


In [99]:
#Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals
array_a = np.random.randint(0,10, size = [3,3])
array_b = np.random.randint(0, 20, size = [3,3])
array_c = np.dot(array_a, array_b)
print("array a is", array_a)
print("array b is", array_b)
print("the dot product of 2 arrays is", array_c)

np.sum(array_c)

#Stack array_a and array_b vertically
np.stack([array_a, array_b], axis= 2)


array a is [[5 6 3]
 [6 9 4]
 [2 5 1]]
array b is [[ 4  1  3]
 [ 6 16 16]
 [ 4 16  1]]
the dot product of 2 arrays is [[ 68 149 114]
 [ 94 214 166]
 [ 42  98  87]]


array([[[ 5,  4],
        [ 6,  1],
        [ 3,  3]],

       [[ 6,  6],
        [ 9, 16],
        [ 4, 16]],

       [[ 2,  4],
        [ 5, 16],
        [ 1,  1]]])

# Create the following pattern without hardcoding. Use only NumPy  functions.


In [107]:
array_repeat = np.concatenate(np.repeat([1,2,3, (1,2,3)], 3), axis = None) #create the repeated array with then flatten the dimension with axis  = None
print(array_repeat)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating  items present in array b


In [146]:
array_a = [1,2,3,4,5]
array_b = [4,5,6,7,8,9]

In [136]:
# First solution
array_bb = [4,5,6,7,8,9] #Clone array_b to avoid "list index out of range error"
for i in array_a:
    for j in range(len(array_b)):
        if i == array_b[j]:
         array_bb.remove(array_b[j]) #if use array_b here, there would be "list index out of range error"

print(array_bb)

[6, 7, 8, 9]


In [140]:
# Second solution (simple):
for i in array_a:
    for j in array_b:
        if i == j:
         array_b.remove(j)

print(array_b)

[6, 7, 8, 9]


# 3. Get all items between 3 and 7 from a and b and sum them together


In [175]:
array_a = [1,2,3,4,5]
array_b = [4,5,6,7,8,9]

In [176]:
for i in array_a.copy(): # to avoid skipping issue caused if using original array
    if i < 3:
        array_a.remove(i) #remove all elements < 3 in array_a

for i in array_b.copy(): #similar
    if i < 3 or i > 7:
        array_b.remove(i) #similar

print(array_a, array_b)
np.sum([np.sum([array_a, array_b])], dtype=object)

[3, 4, 5] [4, 5, 6, 7]


34